- name: Install Grafana Agent
  hosts: all
  become: true

  vars:
    grafana_cloud_api_key: "{{ group_grafana_cloud_api_key }}"
    metrics_username: "{{ group_prometheus_username }}"
    logs_username: "{{ group_loki_username }}"
    prometheus_url: "{{ group_prometheus_url }}"
    loki_url: "{{ group_loki_url }}"
    grafana_agent_version: '0.39.2'
    #grafana_agent_user_groups:
    grafana_agent_mode: static

  tasks:
    - name: Install Grafana Agent
      ansible.builtin.include_role:
        name: grafana.grafana.grafana_agent
      vars:
        grafana_agent_metrics_config:
          configs:
            - name: integrations
              remote_write:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ metrics_username }}'
                  url: '{{ prometheus_url }}'

          global:
            scrape_interval: 60s
            external_labels:
              hostname: ${HOSTNAME:-default}
          wal_directory: /tmp/grafana-agent-wal
        grafana_agent_logs_config:
          configs:
            - name: default
              clients:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ logs_username }}'
                  url: '{{ loki_url }}'
              positions:
                filename: /tmp/positions.yaml
              target_config:
                sync_period: 10s
              scrape_configs:
                - job_name: varlogs
                  static_configs:
                    - targets: [localhost]
                      labels:
                        instance: ${HOSTNAME:-default}
                        hostname: ${HOSTNAME:-default}
                        job: varlogs
                        __path__: /var/log/*log
        grafana_agent_integrations_config:
          node_exporter:
            enabled: true
            instance: ${HOSTNAME:-default}
          prometheus_remote_write:
            - basic_auth:
                password: '{{ grafana_cloud_api_key }}'
                username: '{{ metrics_username }}'
              url: '{{ prometheus_url }}'
        grafana_agent_env_vars:
          HOSTNAME: '%H'