- name: Install Grafana Agent
  hosts: all
  become: true

  vars:
    grafana_cloud_api_key: "{{ group_grafana_cloud_api_key }}"
    metrics_username: "{{ group_prometheus_username }}"
    logs_username: "{{ group_loki_username }}"
    prometheus_url: "{{ group_prometheus_url }}"
    loki_url: "{{ group_loki_url }}"
    grafana_agent_version: '0.39.2'
    #grafana_agent_user_groups:
    grafana_agent_mode: static

  tasks:
    - name: Install Grafana Agent
      ansible.builtin.include_role:
        name: grafana.grafana.grafana_agent
      vars:
        grafana_agent_metrics_config:
          configs:
            - name: integrations
              remote_write:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ metrics_username }}'
                  url: '{{ prometheus_url }}'

          global:
            scrape_interval: 60s
            external_labels:
              hostname: ${HOSTNAME:-default}
          wal_directory: /tmp/grafana-agent-wal
        grafana_agent_logs_config:
          configs:
            - name: default
              clients:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ logs_username }}'
                  url: '{{ loki_url }}'
              positions:
                filename: /tmp/positions.yaml
              target_config:
                sync_period: 10s
              scrape_configs:
                - job_name: varlogs
                  static_configs:
                    - targets: [localhost]
                      labels:
                        instance: ${HOSTNAME:-default}
                        hostname: ${HOSTNAME:-default}
                        job: varlogs
                        __path__: /var/log/*log
                - job_name: integrations/docker
                  docker_sd_configs:
                    - host: unix:///var/run/docker.sock
                      refresh_interval: 5s
                  relabel_configs:
                    - action: replace
                      replacement: integrations/docker
                      target_label: job
                    - action: replace
                      replacement: ${HOSTNAME:-default}
                      target_label: instance
                    - source_labels:
                        - __meta_docker_container_name
                      regex: '/(.*)'
                      target_label: container
                    - source_labels:
                        - __meta_docker_container_log_stream
                      target_label: stream
        grafana_agent_integrations_config:
          node_exporter:
            enabled: true
            instance: ${HOSTNAME:-default}
          prometheus_remote_write:
            - basic_auth:
                password: '{{ grafana_cloud_api_key }}'
                username: '{{ metrics_username }}'
              url: '{{ prometheus_url }}'
          cadvisor:
            enabled: true
            docker_only: true
            instance: ${HOSTNAME:-default}
            relabel_configs:
              - action: replace
                replacement: integrations/docker
                target_label: job
            metric_relabel_configs:
              - action: keep
                regex: container_cpu_usage_seconds_total|container_fs_inodes_free|container_fs_inodes_total|container_fs_limit_bytes|container_fs_usage_bytes|container_last_seen|container_memory_usage_bytes|container_network_receive_bytes_total|container_network_tcp_usage_total|container_network_transmit_bytes_total|container_spec_memory_reservation_limit_bytes|machine_memory_bytes|machine_scrape_error
                source_labels:
                  - __name__
        grafana_agent_env_vars:
          HOSTNAME: '%H'